services:
  mysql:
    image: mysql:8.4
    container_name: estapar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estapar
      MYSQL_USER: estapar
      MYSQL_PASSWORD: estapar
    ports:
      - "3306:3306"
    volumes:
      - estapar-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  garage-sim:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar-garage-sim
    platform: linux/amd64
    ports:
      - "8081:3000"
    environment:
      CLIENT_WEBHOOK_URL: http://host.docker.internal:3003/webhook
      ENTRY_INTERVAL_SECS: "10"
      EXIT_INTERVAL_SECS: "300"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build: .
    image: estapar-parking:dev
    container_name: estapar-app
    profiles: ["app"]
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      garage-sim:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/estapar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&sessionVariables=innodb_lock_wait_timeout=5
      SPRING_DATASOURCE_USERNAME: estapar
      SPRING_DATASOURCE_PASSWORD: estapar
      ESTAPAR_SIMULATOR_BASE_URL: http://garage-sim:3000
    ports:
      - "3003:3003"

volumes:
  estapar-mysql-data:
