ALTER TABLE parking_sessions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE spots            ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sectors          ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
